title: Jasmine Campos Resume
author: Jasmine Campos
email: jasmine.e.campos@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Jasmine's online resume

# social links
github_username:  jascamp # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
